server:
  port: 8901

spring:
  application:
    name: auth-server

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true  # true 或 false 均可，取决于是否希望将它注册到 Eureka server
    fetchRegistry: true  # 需要调用其他服务，所以需要从Eureka拉取服务注册信息
    serviceUri:
      defaultZone: http://localhost:8761/eureka

security:
  oauth2:
    client:
      demo-client:
        clientId: demo-client
        clientSecret: $2a$10$Bgu/e5jk2nXEPurvvPUcqugWv7pspiya.s9TAvTtbY6wtwjKl5qXq
        scope: all
        registeredRedirectUri: http://www.baidu.com
        authorizedGrantTypes: authorization_code, refresh_token, password

logging:
  level:
    org.springframework.security: DEBUG