server:
  port: 8080

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 开启 /actuator/routes 端点，可以访问该端点查看路由信息

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true  # true 或 false 均可，取决于是否希望将它注册到 eureka server
    fetchRegistry: true # 必须为true，否则路由失败： com.netflix.client.ClientException: Load balancer does not have available server for client
    serviceUri:
      defaultZone: http://localhost:8761/eureka

# 使用了Spring Cloud Config 外部化路由配置，因此下面被被注释掉
#zuul:
#  add-host-header: true # 设置为true重定向是会添加host请求头
#  ignored-services: score-service # 关闭默认路由配置
#  routes: # 配置路由规则
#    score-service:
#      path: /scoreService/**  # 将来自 /scoreService/** 的请求路由到由 Eureka 管理的 score-service 服务
#    account-service:  # 静态路由，可以路由到不受 Eureka 管理的服务，直接路由到指定URL
#      path: /accountService/**
#      url: http://localhost:8082

logging:
  level:
    org.springframework: DEBUG