server:
  port: 8082

spring:
  application:
    name: user-mgmt-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUri:
      defaultZone: http://localhost:8761/eureka