server:
  port: 8761

spring:
  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    registerWithEureka: false  # 不注册自己
    fetchRegistry: false  # 不从自己拉取注册信息
  server:
    waitTimeInMsWhenSyncEmpty: 0  # set as 0 for testing only