server:
  port: 8889
spring:
  profiles:
    active: native  # 使用本地存储文件的方式
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    config:
      server:
        git:  # 使用 Git 存储配置文件，需指定git url和路径
          uri: https://github.com/longyg/spring-cloud-stack-config-repo
          searchPaths: api-gateway, auth-server, user-mgmt-service
        native: # 在本地存储配置文件，需指定本地路径
          searchLocations: file:///C:/ylong/workspace/spring-cloud-stack-config-repo/api-gateway,
                           file:///C:/ylong/workspace/spring-cloud-stack-config-repo/auth-server,
                           file:///C:/ylong/workspace/spring-cloud-stack-config-repo/user-mgmt-service