server:
  port: 8889
spring:
  application:
    name: config-server
  profiles:
    active: native  # 使用本地存储文件的方式
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    config:
      server:
        git:  # 使用 Git 存储配置文件，需指定git url和路径
          uri: https://github.com/longyg/spring-cloud-stack-config-repo
          searchPaths: '{application}'
        native: # 在本地存储配置文件，需指定本地路径
          searchLocations: file:///C:/ylong/workspace/spring-cloud-stack-config-repo/{application}  # {application} is placeholder of application name

eureka:
  client:
    registerWithEureka: true # 注册到Eureka，可以让Spring Boot Admin对其监控
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://10.131.98.87:30010/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: C:\ylong\workspace\IntelliJProjects\spring-cloud-stack\config-server\config-server.log